# Generated by Django 5.1.4 on 2026-05-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('provider', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('avg_salary', models.FloatField(help_text='Average or representative salary figure (catalog units).')),
                ('demand_score', models.PositiveIntegerField(help_text='Demand indicator (e.g. frequency rank from source data).')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='catalog.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='catalog.skill')),
            ],
            options={
                'verbose_name': 'job skill (mandatory)',
                'verbose_name_plural': 'job skills (mandatory)',
                'constraints': [models.UniqueConstraint(fields=('job', 'skill'), name='catalog_jobskill_job_skill_uniq')],
            },
        ),
        migrations.CreateModel(
            name='JobFrameworkAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(help_text='Alternatives with the same job and slot_index form one OR group.')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_alternatives', to='catalog.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_alternatives', to='catalog.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'slot_index', 'skill'), name='catalog_jobframework_job_slot_skill_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='catalog.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='catalog.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'skill'), name='catalog_courseskill_course_skill_uniq')],
            },
        ),
    ]
