# Generated by Django 6.0.5 on 2026-06-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sector',
            field=models.CharField(blank=True, help_text='Market sector this job belongs to', max_length=255, null=True),
        ),
    ]
